version: '3.1'
services:
    db:
        image: postgres
        restart: always
        volumes:
            - ~/data/rg-data/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=mydbuser
            - POSTGRES_PASSWORD=mydbpassword
            - POSTGRES_DB=resgen-db
    redis:
        image: "redis:alpine"

    resgen:
        depends_on:
            - "db"
            - "redis"
        command: bash -c "bash -c '/home/resgen/projects/prepare.sh'; /home/resgen/projects/wait-for-it/wait-for-it.sh db:5432 -- supervisord -n"
        image: "pkerpedjiev/resgen:latest"
        ports:
            - 8999:80
        volumes:
            - ~/data/rg-data/:/data
            - ~/data/rg-tmp/:/tmp
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - RESGEN_SERVER_DB_NAME=resgen-db
            - RESGEN_SERVER_DB_HOST=db
            - RESGEN_SERVER_DB_USER=mydbuser
            - RESGEN_SERVER_DB_PASSWORD=mydbpassword
            - RESGEN_AWS_BUCKET=resgen-test
            - RESGEN_AWS_BUCKET_PREFIX=tmp
            - RESGEN_AWS_BUCKET_MOUNT_POINT=aws
        container_name: "resgen-container"
        privileged: true
        secrets:
            - secret_access_key_personal
            - access_key_id_personal

secrets:
    access_key_id_personal:
        file: ~/.aws/access_key_id_personal
    secret_access_key_personal:
        file: ~/.aws/secret_access_key_personal
