version: '3.1'
services:
    redis:
        image: "redis:alpine"
        volumes:
            -  ~/data/redis-data:/data
            -  ~/projects/higlass-docker/redis-context/redis.conf:/usr/local/etc/redis/redis.conf

    higlass:
        depends_on:
            - "redis"
        command: bash -c "supervisord -n"
        image: "pkerpedjiev/higlass:test"
        ports:
            - 8999:80
        volumes:
            - ~/data/hg-data/:/data
            - ~/data/hg-tmp/:/tmp
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        container_name: "higlass-container"
